spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: product
            uri: http://localhost:8090
            predicates:
              - path=/api/v1/products/**
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8022
