spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8091

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1